### ISSUE TITLE
Redirect loop.

### ISSUE THREAD

**Issue by majjoha** [54bricks/54bricks.github.io#1]
Der er et loop ved omdirigering, når man besøger [54bricks.com](http://54bricks.com). Er vores CNAME record sat ordentligt op?

![skrmbillede 2014-03-03 kl 07 55 05](https://f.cloud.github.com/assets/233988/2307115/c9840b42-a2a0-11e3-8709-2de5e56fb5b5.png)

**Comment by jkelstrup** [comment]
Nope, der var en fjollet fejl. CNAME i repoet hed 54bricks.com og vores DNS var sat op til at redirecte 54bricks.com til www.54bricks.com som så CNAMEr til 54bricks.github.io. Hvilket gav loopet. Det rettet nu.
